name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install
        run: |
          mkdir -p .cache/bin
          curl -sSLf "https://dl.filippo.io/mkcert/latest?for=linux/amd64" -o .cache/bin/mkcert
          chmod +x .cache/bin/mkcert
          npm ci

      - name: "Prepare"
        run: |
          export PATH="$PATH:${PWD}/.cache/bin"
          npm run ensure-ca
          npm run issue-cert

      - name: "Build"
        run: |
          npm run build:production

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist

  deploy-green:
    name: "Deploy: green"
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: green
      url: https://demo.engity.green
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name=demo-engity-green dist/green

  deploy-red:
    name: "Deploy: red"
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: red
      url: https://demo.engity.app
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name=demo-engity-red dist/red
