name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request: { }

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          node --version
          npm ci

      - name: "Build"
        run: |
          npm run build:production

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy-green:
    name: "Deploy: green"
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'
    environment:
      name: green
      url: https://demo.engity.green
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name=demo-engity-green dist/green

  deploy-red:
    name: "Deploy: red"
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: red
      url: https://demo.engity.app
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --project-name=demo-engity-red dist/red
